[project]
name = "ai-features-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx==0.26.0",
    "huggingface-hub>=1.3.4",
]
